---
title: "EV Power - Lab 4 Project Report"
author: "David Lee"
format: typst
---

# Example Solution 1

## **Part 0: libraries**

```{r}
library(tidyverse)
library(stringr)
library(leaflet)
library(sf)
library(maps)
library(rnaturalearth)


```

## **Part 1:** **Defining Research Question**

Chosen Question:
Do states with higher shares of electricity that comes from clean sources have lower average electricity prices?

## **Part 2: Data Preparation and Cleaning**

```{r}
#Load datasets relevant to Renewable energy usage, energy prices, and total energy usage
avg_energy_prices = read_csv("data/av-energy-price-2021-2023.csv")
renewable_energy_usage_2021 = read_csv("data/renew-use-2021.csv")
renewable_energy_usage_2022 = read_csv("data/renew-use-2022.csv")
renewable_energy_usage_2023 = read_csv("data/renew-use-2023.csv")
total_energy_usage_2021 = read_csv("data/total-use-2021.csv")
total_energy_usage_2022 = read_csv("data/total-use-2022.csv")
total_energy_usage_2023 = read_csv("data/total-use-2023.csv")


#Standardize Columns. 
total_energy_usage_2021 <- total_energy_usage_2021 |>
    rename()




#Renewable_Energy_Usage data is very messy. Standardized Units? ($, KWH, etc)
#Create a tidy dataframe with col:
#Cols: State, Coal, Natural Gas, Petroleum (BTU), nuclear, total_renewable_energy
#Currently each state has a col, with rows for each energy source. I want to flip this. 

#Transform dataset 
# state (abbrev)
#make a pivot_longer for total_energy_usage for each year
#I want each column of 53 locations (50 states and 1 cumulative USA) to be a separate data entry for each usage. 

tidy_2021_energy_usage <- total_energy_usage_2021 |>
    pivot_longer(cols = 2:length(total_energy_usage_2021), names_to = "state", values_to = "values") |> 
    pivot_wider(names_from = "Energy_Source", values_from = "values") |>
    mutate(year = 2021)
# ---- replicate for 2022 ------
tidy_2022_energy_usage <- total_energy_usage_2022 |>
    pivot_longer(cols = 2:length(total_energy_usage_2022), names_to = "state", values_to = "values") |> 
    pivot_wider(names_from = "Energy_Source", values_from = "values") |>
    mutate(year = 2022)

# ---- replicate for 2023 ------
tidy_2023_energy_usage <- total_energy_usage_2023 |>
    pivot_longer(cols = 2:length(total_energy_usage_2023), names_to = "state", values_to = "values") |> 
    pivot_wider(names_from = "Energy_Source", values_from = "values") |>
    mutate(year = 2023)


# STANDARDIZE Column Names OR add another column with Year. Then merge all data frames together to create panel data

STANDARDIZED_COLUMN_NAMES <- c("State", "Coal Consumption", "Natural Gas", "Petroleum (BTU)", "Nuclear Energy", "Total Renewable Energy", "Year")

colnames(tidy_2023_energy_usage) = STANDARDIZED_COLUMN_NAMES
colnames(tidy_2022_energy_usage) = STANDARDIZED_COLUMN_NAMES
colnames(tidy_2021_energy_usage) = STANDARDIZED_COLUMN_NAMES

### CLEAN avg_energy_prices -> turn each row of STATE(abbrev), AMOUNT (unstructured), 
#STATE, YEAR (2021-2023)
## ie., CA, 2021 amount per million BTU, 2022 amount per million BTU, 2023 amount per million BTU

#STATE ABBREVIATION: "^[A-Z]{2}"
# Amount per million BTU: /d*//./d*
#\d*\.\d*
tidy_avg_energy_prices <- avg_energy_prices |>
    separate_wider_delim(
    "Total energy average price, dollars per million Btu,,,",
    delim = ",",
    names = c("State", "2021", "2022", "2023")
    ) |>
    #Filters empty/header row
    filter(!State %in% c("", "State", NA)) |>
    #extract numeric values 
    mutate(
        across('2021':'2023', ~parse_number(.x))
    ) |>
    pivot_longer(cols = c("2021", "2022", "2023"), names_to = "Year", values_to = "Avg_Energy_Price") |> 
    mutate(Year = as.double(Year), Avg_Energy_Price = Avg_Energy_Price/1000000)
#Price PER MILLION IS NOW PRICE PER BTU
    




```

## **Part 3: Joining / Pivoting Datasets for Analysis**

```{r}
#combine yearly files into single tables as needed

#Document whcih method you chose and why. Create new variables such as % of renewable ernergy out of total energy, ratio of EV registrations, etc

#combine 2021, 2022, 2023 data to have panel data. 
joined_energy_usage <- bind_rows(tidy_2021_energy_usage, tidy_2022_energy_usage, tidy_2023_energy_usage) 

single_table <- left_join(joined_energy_usage, tidy_avg_energy_prices, by = c("State", "Year")) |>
   # mutate(Total_Coal_Price = Avg_Energy_Price * `Coal Consumption`, Total_Natural_Gas_Price = Avg_Energy_Price * `Natural Gas`, Total_Petroleum_Price = Avg_Energy_Price * `Petroleum (BTU)`, Total_Nuclear_Energy_Price = Avg_Energy_Price * `Nuclear Energy`, Total_Renewable_Energy_Price = Avg_Energy_Price * `Total Renewable Energy`) |> #Total Price of Fuel for Components
    mutate(Total_Non_Renewable_Energy_Usage = `Coal Consumption`+ `Natural Gas` + `Petroleum (BTU)` + `Nuclear Energy`) |> #Total Non Renewable Energy Usaeg
    mutate(Total_Energy_Usage = Total_Non_Renewable_Energy_Usage + `Total Renewable Energy`) |> #Total Energy Usage
    mutate(Proportion_of_Renewable_Energy = `Total Renewable Energy`/Total_Energy_Usage) |>
    select(State, `Total Renewable Energy`, Year, Avg_Energy_Price, Proportion_of_Renewable_Energy)

```

## **Part 4: Mapping Visualization**

```{r}
#df <- single_table |>
#    mutate(Year = as.integer(Year)) 
#us_states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))

test_2021_table <- single_table |>
    filter(Year == 2021)

us_states <- ne_states(country = "united states of america", returnclass = "sf")
us_joined <- us_states |>
    right_join(test_2021_table, by = join_by("postal"=="State")) 
#Plot and Color by Proportion
ggplot(us_joined) +
    geom_sf(aes(fill=Proportion_of_Renewable_Energy), color = "white") +
  scale_fill_continuous(name = "Proportion_of_Renewable_Energy", na.value = "grey90") +
  labs(title = "Proportion of Renewable Energy by States") +
  coord_sf(xlim = c(-125, -66), ylim = c(24, 50), expand = FALSE) +
  theme_minimal()

```